### ISSUE TITLE
Error when setting trust line flag in Stellar Lab

### ISSUE THREAD

**Issue by Gurumahajava** [stellar/laboratory#1042]
### What version are you using?
I am using the currently released version of the Stellar labs that is currently available at https://lab.stellar.org/  

### What did you do?
Attempted to set a trust line flag on an account via Stellar lab, received an error message and had to find a workaround

Navigate to https://lab.stellar.org/
Select the transaction tab
Build a "Set Trust Line Flag" transaction
Select "Alphanumeric 4" for Asset , enter an "Asset Code", "Issuer Account ID" and "Trustor"
Select "Authorized" for Set Flags
Notice that the "Transaction Envelope XDR Error:" = missing field clear_flags at line 1 column 438
Select "Authorized" for Clear Flags
Notice that XDR now = Success! Transaction Envelope XDR:
De-select "Authorized" for Clear Flags
Notice that XDR still = Success! Transaction Envelope XDR:

### Expected Behaviour ?
I expected to be able to "Set Flags" when building a trust line for an account without having to select and de-select "Authorized" for "Clear Flags" in order to get rid of the unexpected error message.

### Actual Behaviour
When building a trust line for an account if you want to "Set Flags" you get an unexpected error which you can only resolve by selecting and de-selecting "Authorized" for "Clear Flags" 
 
### Related issue
There is a second variant of this bug, if you wanted to set a "Clear Flag" you would get a similar error which you can then resolve by selecting and de-selecting "Authorized" for "Set Flags".

**Comment by quietbits** [comment]
@Gurumahajava, thanks for opening this issue. Is your intent to create a trustline for an account that doesn't have this trustline yet? Or modify an existing trustline?
- [Set trustline flags](https://developers.stellar.org/docs/learn/fundamentals/transactions/list-of-operations#set-trustline-flags) is to modify a trustline.
- [Change trust](https://developers.stellar.org/docs/learn/fundamentals/transactions/list-of-operations#change-trust) create new trustline.

P.S. The link to Opeation type docs was wrong in the Lab. Fixed in [this PR](https://github.com/stellar/laboratory/pull/1044).

**Comment by Gurumahajava** [comment]
Hello quietbits, my intention was to create a trustline for an account that doesn't have a trustline. You can also simply recreate this error by following the steps for the Stellar Quests, Level 02, Configuration Operations, Set Flags. https://quest.stellar.org/learn

**Comment by quietbits** [comment]
Thanks for the extra details, @Gurumahajava , that's very helpful. I see that it's not working as expected.
