### ISSUE TITLE
Guide users after account creation

### ISSUE THREAD

**Issue by litnerdy** [stellar/laboratory#149]
The new account creation functionality in the Lab is great. When users reach the end of that flow, hopefully they'll continue to explore the Lab's other features, like building a transaction. I'd love to see a CTA button appear after the account is funded with something like "Build a transaction" (or whatever we want them to do after funding the account). What do folks think? @mozzadrella maybe this will be impacted by user testing, and maybe we can figure out what the logical next step would be from that. cc @irisli 

![stellar_laboratory](https://cloud.githubusercontent.com/assets/8799534/14537647/b71069e0-022c-11e6-8cb0-6fa219983f61.png)

**Comment by nullstyle** [comment]
As we add tutorials, I think we should be careful about turning this _tool_ into a _tutorial_.  

I'm fine with adding tutorials specifically about the lab, but I'm wary about adding tutorials that are primarily about learning the capabilities of the stellar network:  I think doing so will add friction to using the tool and we would be better served through a more dedicated developer tutorial.

This distinction I'm trying to express is subtle, so let me try to explain further with some examples.  Let me define two groups:  tutorials about the lab (good), and tutorials about stellar (bad).

good:  "learn how to craft transactions using the transaction builder"
bad: "learn what transactions are and how sending them causes changes to the ledger"

good: "learn how to add signatures to a transaction envelope using the signer tool"
bad: "learn about private keys"

good: "learn how to use the endpoint explorer to load your account's current details"
bad: "learn how signature thresholds work"

As you can hopefully see, the "good" tutorials are all centered on learning something specific about how the lab operates and how you might use it to help your stellar development experience, rather than getting to know some feature of the stellar network. Note: I'm fine with linking off to additional resources to help teach people about our network's capability, I am simply wary about bogging down the tool with too much narrative or other guided experiences.

---

I'd also like to point out some early motivations we agreed to around the creation of the laboratory.  Specifically, we decided that the laboratory is first a tool to help developers that are integrating with the stellar network and secondly it is a way to teach developers about the capabilities of the network through exploration.  The lab isn't meant to be a single experience to be completed(i.e. a tutorial), but rather something that a stellar developer will use daily...  at this point I do and it is a huge boon.  I would be sad if we compromise its utility to improve our tutorials.

---

All of that said, I don't have any specific issue with the addition being proposed in this issue.

**Comment by irisli** [comment]
I agree that we should be careful about adding too much tutorial pieces to generic tools. It adds to the thought load and can distract users following a tutorial that goes a different direction as the build in tutorial in the laboratory.

---

The account creator has the ability to create accounts and the next step could be many different things. By adding a next steps item to a generic tool, it can mislead those following another tutorial that does not follow the same route as the one we build into the tool.

**Comment by vcarl** [comment]
Closing this as it's very old. This is something we'll keep in mind as we plan and implement a larger overhaul at some point in the future.
