### ISSUE TITLE
Feature Request: Update TransactionBuilder to support FeeBumpTransactions

### ISSUE THREAD

**Issue by abuiles** [stellar/laboratory#445]
The following table on `TransactionSigner` needs to be updated to support `FeeBumpTransaction`:

```
      let infoTable = {
        'Signing for': <pre className="so-code so-code__wrap"><code>{networkPassphrase}</code></pre>,
        'Transaction Envelope XDR': <EasySelect plain={true}><pre className="so-code so-code__wrap"><code>{xdr}</code></pre></EasySelect>,
        'Transaction Hash': <EasySelect plain={true}><pre className="so-code so-code__wrap"><code>{transaction.hash().toString('hex')}</code></pre></EasySelect>,
        'Source account': transaction.source,
        'Sequence number': transaction.sequence,
        'Transaction Fee (stroops)': transaction.fee,
        'Number of operations': transaction.operations.length,
        'Number of existing signatures': transaction.signatures.length,
      };
```

If the transaction is fee bump, then we need to show details from the inner and outer transaction.

**Comment by accordeiro** [comment]
The high-level description is:

Users should be able to create a Fee Bump operation in the Lab, inspect it, submit, and see the response. @ire-and-curses mentioned that it seems the xdr-viewer in the Lab already parses a submitted fee bump correctly (see e.g. [this fee bump tx](https://laboratory.stellar.org/#xdr-viewer?input=AAAABQAAAAC3wy932uaOQEtbnXPimf4Xj5vyI9MVQR2yVWIHgOqKAAAAAAAAAAJYAAAAAgAAAAC3wy932uaOQEtbnXPimf4Xj5vyI9MVQR2yVWIHgOqKAAAAAGQBg0k6AAAAWgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAA9IYXBweSBiaXJ0aGRheSEAAAAAAQAAAAAAAAABAAAAALfDL3fa5o5AS1udc%2BKZ%2FhePm%2FIj0xVBHbJVYgeA6ooAAAAAAAAAAAAAmJaAAAAAAAAAAAGA6ooAAAAAQOVkZlEgLoTa7TmFtSjP7UTYXFVVZ6FM1oBSmPvLp1jypZ0Sq4zh0QGz5HoH8APoIpLeldGmNuofMAuLVGTeBQQAAAAAAAAAAYDqigAAAABAVsqWFOcMBw%2B2Db%2B0SEwN%2FeiQc%2FUBHVSJydhdkRVt%2FBzdLkFSxVIi5EMTVDHcFpF7865coq1ir4TTXy9y4j17Aw%3D%3D&type=TransactionEnvelope&network=public)).

@vcarl will share some notes on what the new UI might need.

**Comment by acharb** [comment]
@abuiles I believe this issue was completed here https://github.com/stellar/laboratory/commit/b5222da7be0be48c0906ca7f688958a9116ac487

I'll leave the issue open for the UI/UX changes though

**Comment by vcarl** [comment]
Yeah that's half of it, to properly parse the XDRs for signing. I believe they have to be created directly with the SDK at the moment, though.

As for the UI, since this is a new type of transaction, I think the UI for it is a little harder than other recent changes. My first thought is a new top-level form for the transaction builder, with a toggle between a normal transaction and a fee bump transaction

<img width="1118" alt="Screen Shot 2020-06-25 at 10 32 16 AM" src="https://user-images.githubusercontent.com/1551487/85740068-504e0f80-b6cf-11ea-8e05-cf9e5a66b824.png">

When fee bump is selected, the form could change as below

<img width="1116" alt="Screen Shot 2020-06-25 at 10 31 28 AM" src="https://user-images.githubusercontent.com/1551487/85740142-5fcd5880-b6cf-11ea-90a7-236a6e22fd3d.png">

Because no operations can be added to a fee bump transaction, the "add operation" UI should be hidden on this screen as well. I just pulled in the list of fields/descriptions from [the docs](https://stellar.github.io/js-stellar-sdk/TransactionBuilder.html#.buildFeeBumpTransaction) and gave it a sane form input—it might make more sense to leave off the network passphrase input and just pull it from the active network, but I thought of that after taking the screenshot haha

**Comment by accordeiro** [comment]
Nice @vcarl, thanks so much for putting these together! @acharb do you have everything you need to work on this now? Please let me know if any other info is missing.

**Comment by abuiles** [comment]
@vcarl what about adding the fee bump at the bottom instead of making them separate?

**Comment by vcarl** [comment]
Fee bump transactions don't need a sequence number, memo, or time bounds, right? I was thinking it'd be clearest to remove any fields that aren't necessary.

**Comment by acharb** [comment]
@vcarl this makes sense to me. I think I see @abuiles point though of putting the option of adding a fee bump transaction after creating the inner transaction, since the inner transaction has to be created first?

What if the option to add a fee bump was added under the "submit transaction" tab? So once the inner transaction is created and signed, you have the option to add a fee bump at the end?

**Comment by abuiles** [comment]
Another thing to keep in mind is that the inner transaction and the fee bump transaction might be created at different times. 

So we probably need two modes:

1. You want to create an inner transaction and fee bump transaction at the same time.
2. You are given an inner transaction (base64 encoded XDR) and want to wrap it in a fee bump tx. 

In the second scenario we probably need to give people a way to load the inner tx from a base64 string and some how end up in this screen https://laboratory.stellar.org/#txbuilder -- so you can see the details of the tx you are fee bumping and complete the details for the fee bump transaction.

**Comment by vcarl** [comment]
Creating both at the same time seems like an odd use case though—if you're creating a new transaction, you can set the fee to whatever you want

**Comment by vcarl** [comment]
Chatted privately about this, additional use case I hadn't considered is paying the fee on someone else's behalf, which is a real reason to create both at the same time. The inner transaction needs to be signed, so I think it makes the most sense to add that as a link from the TransactionSigner screen -> TransactionBuilder with prefilled state.

<img width="1134" alt="Screen Shot 2020-06-25 at 1 03 01 PM" src="https://user-images.githubusercontent.com/1551487/85774179-96659c00-b6ec-11ea-8a82-5d9a51560ad5.png">

@acharb some prior art for how those links are created is in #450, specifically the changes to [`linkBuilder.js`](https://github.com/stellar/laboratory/pull/450/files#diff-807c4047af76c507f8695a1c8d93e494) and [`stateSerializer.js`](https://github.com/stellar/laboratory/pull/450/files#diff-07ee40d346bf06669a6da9c7542636ee)
