### ISSUE TITLE
vendor.bundle.js is not fingerprinted and given a unique filename during build

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#447]
### What version are you using?

944f1a6b8627ee47b515fe9deb0811201d9b246a

### What did you do?

Went to https://laboratory.stellar.org.

### What did you expect to see?

The laboratory.

### What did you see instead?

A blank white page.

### What happened?

@bartekn identified that `vendor.bundle.js` in the built code isn't assigned a unique filename by hashing the contents of the file and including that hash in the filename. The `app.js` file is already fingerprinted.

This causes browsers and any CDN placed in front of a hosted laboratory to potentially cache a version of the vendor bundle that is incompatible with app.js. When this happens the app might break, or fail to load as it did today.

Thanks @bartekn @abuiles for help hunting down the cause of this.

**Comment by vcarl** [comment]
This is a little odd, because the contents of that file shouldn't be changing ([the contents are hardcoded](https://github.com/stellar/laboratory/blob/master/webpack.config.base.js#L8) to a couple of dependencies). That's a relatively older strategy for splitting bundles, and we're on an older versinon of Webpack, so I'll see if we can update

**Comment by leighmcculloch** [comment]
This happened when the stellar-sdk was updated.

**Comment by vcarl** [comment]
#448 has no dep changes tho, and apparently we had cache issues again yesterday.

**Comment by abuiles** [comment]
> #448 has no dep changes tho, and apparently we had cache issues again yesterday.

Maybe they they had an old version in their local cache?
