### ISSUE TITLE
Feature Request: warn when signer weights will be set to 0

### ISSUE THREAD

**Issue by vcarl** [stellar/laboratory#463]
### What problem does your feature solve?

Setting an account's only signer weight to 0 permanently locks that account. This is a feature of the Stellar network, but it's also a footgun: There's no way to undo this, and it happens be done without any confirmation. It's very common when experimenting with issuing a new asset, for instance.

### What would you like to see?

When setting the master signing weight, or medium/high operation threshold ([example Lab page](https://laboratory.stellar.org/#txbuilder?params=eyJhdHRyaWJ1dGVzIjp7ImZlZSI6IjEwMCJ9LCJvcGVyYXRpb25zIjpbeyJpZCI6MCwiYXR0cmlidXRlcyI6eyJtYXN0ZXJXZWlnaHQiOiIwIiwibG93VGhyZXNob2xkIjoiIiwibWVkVGhyZXNob2xkIjoiMCIsImhpZ2hUaHJlc2hvbGQiOiIwIiwiaW5mbGF0aW9uRGVzdCI6IiJ9LCJuYW1lIjoic2V0T3B0aW9ucyJ9XX0%3D&network=test)), the Laboratory should warn the user about the dangers of doing so, and provide a link to documentation or other resources.

![Screen Shot 2020-06-29 at 6 09 21 PM](https://user-images.githubusercontent.com/1551487/86060887-b02c1980-ba33-11ea-886c-8cedf1f9659a.png)

### What alternatives are there?

Let people keep bricking their accounts by accident 🙂

**Comment by ire-and-curses** [comment]
There are some other edge cases related to this that can be worth considering. See the discussion here: https://github.com/stellar/docs/issues/486


- if you set your master key weight to 0, it's game over - you can't do anything any more. Everything is now read-only.
- if you change the "high" threshold to a number larger than your master key weight, you lose all ability to change options in the future. In particular this means you can't add or remove new signers or adjust thresholds for the account. Effectively you've frozen the account's access permissions.
- if you also change the "medium" threshold to exceed the master key weight it's even worse - now you can't transfer funds out of your account at all (Payment is a medium threshold operation)!
- another, less bad but not obvious example. You set your low threshold too high and now you can't charge fees from that account. The fix is to pay for the Tx with a second account - but you might conclude that you were just dead in the water.
