### ISSUE TITLE
Transaction fee isn't optional

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#49]
Can you replace "(optional)" with "(100 per operation)"

**Comment by irisli** [comment]
The `(optional)` refers to the field being optional because it's added behind the scene if nothing is filled in.

I'm not sure `(100 per operation)` is clear because it's ambiguous to me. Are we trying to say that the minimum for the whole transaction is 100 stroops per operation? Or are we merely suggesting.

It's optional because we default to 100 per operation (I think).

We should then also clarify that that field is for the whole transaction or it will be multiplied by each operation.

Can you add more details on how we can make this more clear while still not too complicated to use?

**Comment by irisli** [comment]
Is there anything to add or clarify to this?

![image](https://cloud.githubusercontent.com/assets/5728307/12629864/83772954-c4fe-11e5-9d76-e559880d400d.png)
