### ISSUE TITLE
Error when creating a transaction with a starting balance of 0

### ISSUE THREAD

**Issue by shanzzam** [stellar/laboratory#500]
With the implementation of Protocol 15, we should be able to create a transaction with a starting balance of 0.

Currently seeing this error when doing so:
![Screen Shot 2020-12-17 at 11 21 14 AM](https://user-images.githubusercontent.com/5062622/102533384-32e47780-405a-11eb-9ffe-1c92fb0d0c99.png)

[example transaction ](https://laboratory.stellar.org/#txbuilder?params=eyJhdHRyaWJ1dGVzIjp7InNvdXJjZUFjY291bnQiOiJHQ01HUVdNN1VUV0M2S1JRUUlTTVpFU0VKUUlPUUpPMks1TzYyMzZRQkNYVkFUWklBV0QySjRWRyIsInNlcXVlbmNlIjoiMzU1MDEyOTc3MjU2MDM4NSIsImZlZSI6IjEwMCJ9LCJmZWVCdW1wQXR0cmlidXRlcyI6eyJtYXhGZWUiOiIxMDAifSwib3BlcmF0aW9ucyI6W3siaWQiOjAsImF0dHJpYnV0ZXMiOnsic3BvbnNvcmVkSWQiOiJHQkxCRVFBSFE1SlNWVERHN1FWUUVaR0dYSkJYVk9ZVFkyWUZBNkpST1IzNVFTN0xDSVBYN1FUTCJ9LCJuYW1lIjoiYmVnaW5TcG9uc29yaW5nRnV0dXJlUmVzZXJ2ZXMifSx7ImlkIjoxNjA4MjIyMDMzODk4LCJuYW1lIjoiY3JlYXRlQWNjb3VudCIsImF0dHJpYnV0ZXMiOnsiZGVzdGluYXRpb24iOiJHQkxCRVFBSFE1SlNWVERHN1FWUUVaR0dYSkJYVk9ZVFkyWUZBNkpST1IzNVFTN0xDSVBYN1FUTCIsInN0YXJ0aW5nQmFsYW5jZSI6IjAifX1dfQ%3D%3D&network=test)

**Comment by quietbits** [comment]
The [quick fix](https://github.com/stellar/laboratory/pull/502) was to add the correct `js-stellar-base` version (which has the fix for 0 starting balance) manually in Laboratory. The proper fix will be to update `js-stellar-sdk` with the latest `js-stellar-base` and then use the updated `js-stellar-sdk` version in Laboratory.

The latest `js-stellar-sdk` might have breaking changes (going from v6 to v7) and it might be too risky to make that update right now, hence the quick fix.

I'll keep this bug open to make sure we do a proper update and remove `js-stellar-base` from Laboratory.

**Comment by shanzzam** [comment]
@quietbits should we open an issue in js-stellar-sdk to update to the correct base? It seems like that's something that should be done anyway.

**Comment by quietbits** [comment]
@shanzzam My bad, I didn't include the open issue to fix this in `js-stellar-sdk`. It's this one: https://github.com/stellar/js-stellar-sdk/issues/602.
