### ISSUE TITLE
Guess the XDR types in the View XDR page

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#949]
### What problem does your feature solve?
The CLI can do this with `stellar xdr guess`: https://developers.stellar.org/docs/tools/developer-tools/cli/stellar-cli#stellar-xdr

Benefit: help users to to more easily use Lab to parse the XDR

**Comment by janewang** [comment]
@sdfcharles @quietbits  I think the behavior requires some consideration. When we guess the XDR type, the list of XDR types all can decode the XDR but one is correct. Right now the behavior is that the XDR defaults to the first one from a list of XDRs, which decodes but quite possibly isn't the right one. Do you think it makes more sense to show the list and not decode to a specific one?

Here's the PR with a viewable link below: https://github.com/stellar/laboratory/pull/981

**Comment by quietbits** [comment]
> @sdfcharles @quietbits I think the behavior requires some consideration. When we guess the XDR type, the list of XDR types all can decode the XDR but one is correct. Right now the behavior is that the XDR defaults to the first one from a list of XDRs, which decodes but quite possibly isn't the right one. Do you think it makes more sense to show the list and not decode to a specific one?
> 
> Here's the PR with a viewable link below: #981

The guesses are listed in the order of potential match. Meaning that the first item in the list is more likely to be true than the second, etc (@leighmcculloch,  please correct me if I'm wrong here). If we don't use the first guess, we will default to `TransactionEnvelope`.

**Comment by leighmcculloch** [comment]
> The guesses are listed in the order of potential match. Meaning that the first item in the list is more likely to be true than the second, etc (@leighmcculloch, please correct me if I'm wrong here).

Actually the list is not ordered intentionally by any value. The list is created by iterating the variants as defined on the `Type` type, and the order is simply a preservation of the variants as listed on that type:
- https://github.com/stellar/js-stellar-xdr-json/blob/25fa89617937198111d708b22c1ecd2945a6e906/src/lib.rs#L33-L45
- https://github.com/stellar/rs-stellar-xdr/blob/5315f4c583784860c0accbb8d3bd234055a19751/src/curr/generated.rs#L49194-L49223

You could display the list returned in whatever order is preferred.

> default to `TransactionEnvelope`

It sounds like a good idea to have `TransactionEnvelope` at the top of the guess list if something does decode as it.

Maybe use alphabetical sort after then?

**Comment by sdfcharles** [comment]
updated designs here: https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=5186-20833&t=KjF3TKPokUfDfG62-1

<img width="1440" alt="02 View XDR" src="https://github.com/user-attachments/assets/8dfce870-38aa-471d-ad38-d1b197369b61">

the new behavior is that we will default to `TransactionEnvelope` and when an XDR is inputted, add a tag next to every option that would be included in the "Best Guess" list.

because we don't have more data to be able to sort the best guess list, this behavior will default to `TransactionEnvelope`, and if it throws an error, then the user can scroll through and see ones that could be possible types. it's not helpful to the user to click through several options without context and if they aren't giving errors.

**Comment by janewang** [comment]
Thank you for the updated design! @sdfcharles
